### ISSUE TITLE
Hey, wondering if you could open up the gem namespace for bitbot.

### ISSUE THREAD

**Issue by jejacks0n** [zwily/bitbot#4]
I sent you a personal email a few months ago, but I never heard back. Hitting you up again. =)

Wondering if you're planning on doing something with the gem, or if it's pretty much abandoned? It would be awesome if you wanted to open up the namespace for https://github.com/modeset/bitbot which is an active project.

Thanks!

**Comment by zwily** [comment]
@jejacks0n Sorry for the delay - it looks like your original got caught by spam, so I never saw it. Sorry about that. 

I'd be happy to release the gem name, but it's not quite as abandoned as it looks. I know of at least two people actually using the gem now, and I'd hate to pull the rug out from under them. What would happen when they try to upgrade `bitbot` in the future?

I've also started working on adding Slack integration. In fact, I'm considering using your bitbot for that. :)

**Comment by jejacks0n** [comment]
@zwily Haha, rad! Ok, that makes sense and thanks for getting back to me. I'll rename it and release a gem version when I can get around to it.
